version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: "website-backend"
    container_name: "website-backend"
    ports:
      - "5000:5000"
    volumes:
      - ./certs:/app/certs
